apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agniveer.fullname" . }}-config
data:
  APP_NAME: "Agniveer Sentinel"
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  API_V1_PREFIX: "/api/v1"
  POSTGRES_HOST: {{ .Values.global.database.host | quote }}
  POSTGRES_PORT: {{ .Values.global.database.port | quote }}
  POSTGRES_DB: {{ .Values.global.database.name | quote }}
  REDIS_HOST: {{ .Values.global.redis.host | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
  S3_ENDPOINT_URL: {{ .Values.global.s3.endpoint | quote }}
  S3_BUCKET_NAME: {{ .Values.global.s3.bucket | quote }}
  OPENWEATHERMAP_BASE_URL: "https://api.openweathermap.org/data/2.5"
